version: '3.8'

services:
  backend:
    build: ./backened
    container_name: backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80" # React will be available at http://localhost:3000
    restart: always
